### ISSUE TITLE
ERROR: Exception: Traceback - PIP3

### ISSUE THREAD

**Issue by RessBB** [DRACULA-HACK/master-numbers#1]
Hello, I would like to try this software on my PC which is running FossaPup64. Unfortunatelly i have some difficulties with it. To be more concrete i forced these errors in Terminal app:

root# python setup.py
sh: pip: command not found
Traceback (most recent call last):
  File "de.py", line 11, in <module>
    exec(decoded_content)
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'bs4'

then I have tried this command but get another error message:

root# pip3 install -r requirements.txt
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 305, in run
    session = self.get_default_session(options)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 74, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 84, in _build_session
    session = PipSession(
  File "/usr/lib/python3/dist-packages/pip/_internal/network/session.py", line 241, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3/dist-packages/pip/_internal/network/session.py", line 132, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 122, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 677, in linux_distribution
    self.version(),
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 737, in version
    self.lsb_release_attr('release'),
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 899, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 552, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl/distro.py", line 1012, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.

I will really appreciate if anybody helps me solve this, since Im not very experienced in compiling python.
I would really like to test this program also :)))

**Comment by adjeimarvinbruce-jpg** [comment]
It appears you don't have python installed
